# Generated by Django 2.1.5 on 2019-03-13 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Information', models.TextField(max_length=1000)),
                ('Photo', models.ImageField(blank=True, default='download.jpg', null=True, upload_to='Photo')),
                ('IdContinents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Continent')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Flag', models.ImageField(blank=True, default='download.jpg', null=True, upload_to='Flags')),
                ('Latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('Longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('Rating', models.IntegerField(default=0)),
                ('IdContinents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Continent')),
            ],
        ),
        migrations.AddField(
            model_name='information',
            name='IdState',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.State'),
        ),
    ]
