# Generated by Django 2.1.5 on 2019-03-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='Name',
            field=models.CharField(choices=[('ekonomia', 'Ekonomia'), ('turizmi', 'Turizmi'), ('pozita', 'Pozita Gjeografike'), ('klima', 'Klima')], default='ekonomia', max_length=50),
        ),
    ]
