# Generated by Django 2.1.5 on 2019-03-19 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190319_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='IdCategorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Categorie'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='Name',
            field=models.CharField(choices=[('Ekonomia', 'Ekonomia'), ('Turizmi', 'Turizmi'), ('Pozita Gjeografike', 'Pozita Gjeografike'), ('Klima', 'Klima')], default='ekonomia', max_length=50),
        ),
    ]
