# Generated by Django 2.1.7 on 2019-03-22 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190319_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='state',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='information',
            name='IdCategorie',
            field=models.ForeignKey(default='ekonomia', on_delete=django.db.models.deletion.CASCADE, to='home.Categorie'),
        ),
        migrations.AlterField(
            model_name='state',
            name='Flag',
            field=models.ImageField(blank=True, default='download.jpg', height_field='height_field', null=True, upload_to='Flags', width_field='width_field'),
        ),
    ]
