# Generated by Django 2.1.7 on 2019-03-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190322_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='Flag',
            field=models.ImageField(blank=True, default='default.jpg', height_field='height_field', null=True, upload_to='Flags', width_field='width_field'),
        ),
    ]
