# Generated by Django 2.1.7 on 2019-03-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190322_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='Photo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='Photo'),
        ),
    ]
