# Generated by Django 2.1.7 on 2019-03-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190322_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='Photo',
            field=models.ImageField(blank=True, default='download.jpg', null=True, upload_to='Photo'),
        ),
        migrations.AlterField(
            model_name='state',
            name='Flag',
            field=models.ImageField(blank=True, default='download.jpg', height_field='height_field', null=True, upload_to='Flags', width_field='width_field'),
        ),
    ]
