# Generated by Django 2.1.5 on 2019-03-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190322_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
