# Generated by Django 2.1.7 on 2019-03-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_information_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='Flag',
            field=models.ImageField(blank=True, default='download.jpg', height_field='height_field', null=True, upload_to='Flags', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='information',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='information',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
