# Generated by Django 2.1.5 on 2019-03-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190330_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='Name',
            field=models.CharField(choices=[('Ekonomia', 'Ekonomia'), ('Turizmi', 'Turizmi'), ('Gjeografi', 'Gjeografi'), ('Klima', 'Klima'), ('Kulture', 'Kulture')], default='ekonomia', max_length=50),
        ),
    ]
