# Generated by Django 2.1.5 on 2019-03-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190330_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='Name',
            field=models.CharField(choices=[('Ekonomia', 'Ekonomia'), ('Klima', 'Klima'), ('Gjeografi', 'Gjeografi'), ('Kulture', 'Kulture'), ('Turizmi', 'Turizmi')], default='ekonomia', max_length=50),
        ),
    ]
